### PR TITLE
Export `GenConst`

### LINKED ISSUE #36: `GenConst` is part of the public interface, but not exported
[generate_const](https://docs.rs/virtue/0.0.11/virtue/generate/struct.ImplFor.html#method.generate_const) can make `GenConst`, which is [not re-exported in `generate`](https://github.com/bincode-org/virtue/blob/trunk/src/generate/mod.rs#L32) and so has no public documentation.

### PR DESCRIPTION
**Pull request by Daniel-Aaron-Bloom**
fixes #36

### CODE REVIEW

**Comment by VictorKoenders** [comment]
I would merge this but github actions is having a day...

**Comment by VictorKoenders** [comment]
If you fix the missing doc issues, I think this is good to go 👍

**Comment by Daniel-Aaron-Bloom** [comment]
Docs have been added.

**Review by VictorKoenders — APPROVED** [review]
Thanks! This looks great

**Pull request merged**
