### PR TITLE
Export `ConstGeneric`

### LINKED ISSUE #38: `ConstGeneric` is part of the public interface, but is not exported
[`ConstGeneric` ](https://docs.rs/virtue/0.0.11/virtue/parse/enum.Generic.html#variant.Const) is [not re-exported in `parse`](https://github.com/bincode-org/virtue/blob/trunk/src/parse/mod.rs#L15) and so has no public documentation.

### PR DESCRIPTION
**Pull request by Daniel-Aaron-Bloom**
fixes #38

### CODE REVIEW

**Comment by VictorKoenders** [comment]
I would merge this but github actions is having a day...

**Comment by VictorKoenders** [comment]
If you fix the formatting and missing doc issue, I think this is good to go 👍

**Comment by Daniel-Aaron-Bloom** [comment]
I think the docs issue is that `take` was unnecessarily `pub`, so I have `(crate)`d it.

**Review by VictorKoenders — APPROVED** [review]
Thanks!

**Pull request merged**
