### PR TITLE
Treat empty struct fields differently to a unit

### PR DESCRIPTION
**Pull request by mkj**
A Struct { } should have Some(Fields::Struct(vec![])) rather than None.

This partially reverts cfb17c0cac7f19568d575117de3b218539e73ada (#45)

### CODE REVIEW

**Comment by VictorKoenders** [comment]
I'm not sure if this is the right way to go. I'm more inclined to use a library like https://docs.rs/non-empty-vec/latest/non_empty_vec/ to make sure the fields always have a value, and `None` == `struct but 0 fields` == `enum but 0 fields`

Can you come up with a use-case where a developer who is using virtue wants to differentiate between `struct Foo;`, `struct Foo { }` and `struct Foo();`?

**Comment by mkj** [comment]
At the moment I'm using empty-brace syntax for my empty structs, like `NewKeys` below. No particular reason other than consistency with my non-empty structs (they're a set of packet formats).

```rust
#[derive(Debug, SSHEncode, SSHDecode)]
pub struct NewKeys {}

// alternative using a unit struct
#[derive(Debug, SSHEncode, SSHDecode)]
pub struct Ignore;
```

From what I can tell with the new Virtue there isn't a way to distinguish between these two cases in the parser. If I want to generate a constructor for them they need different syntax, `Self {}` vs `Self`. I could just change all of them to be unit structs, but it seems Virtue should be able to express either?

```rust
// generated code
impl<'de> crate::sshwire::SSHDecode<'de> for NewKeys {
    fn dec<S: crate::sshwire::SSHSource<'de>>(
        s: &mut S,
    ) -> crate::sshwire::WireResult<Self> {
        Ok(Self)
    }
}
```

```
52 | #[derive(Debug, SSHEncode, SSHDecode)]
   |                            ^^^^^^^^^ help: use curly brackets: `Self { /* fields */ }`
```

**Comment by mkj** [comment]
Oh, I only just realised the empty brace constructor is fine for any of unit/empty-struct/empty-tuple. So perhaps the current behaviour is fine to leave as-is, any `None` fields variant can use `Self {}`.

```rust
    struct A;
    struct B();
    struct C {};
    let a = A {};
    let b = B {};
    let c = C {};

```

**Comment by VictorKoenders** [comment]
Thinking about it more I think it's probably beneficial to determine between the delimiter even if there's no fields.

There is also an assert [here](https://github.com/bincode-org/virtue/blob/trunk/src/parse/body.rs#L382-L384) that should be removed.

If you can remove that and fix the linting issues I think this is good to merge

**Comment by mkj** [comment]
It turns out `.names()` wasn't getting called at all in tests so I've added that too. Thanks!

**Review by VictorKoenders — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
